"""Email Template"""
EMAIL_TEMPLATE = "pytest_2.0_regression_email@bink.com"

"""Channel User Details"""
UID = "uid"
PWD = "pwd"
USER_DETAIL = "user_detail"
USER_DETAIL2 = "user_detail2"


""" Payment Cards Constant"""
FIRST_SIX_DIGITS = "first_six_digits"
LAST_FOUR_DIGITS = "last_four_digits"
ISSUER = "issuer"
TOKEN = "token"
FINGERPRINT = "fingerprint"
PROVIDER = "provider"
CURRENCY_CODE = "currency_code"
COUNTRY = "country"
TYPE = "type"
TOKEN_2 = "token_2"
TOKEN_PREFIX = "token_prefix"
PAYMENT_CARD_STATUS = "status"


# PAYMENT_CARD_STATUS = "status"
# ACTIVE_LINK = "active_link"
# PAYMENT_PROVIDER = "payment_provider"
# PAYMENT_URL = "payment_url"
# PAYMENT_ENCODING = "payment_encoding"
# PAYMENT_DISCRIPTION = "payment_discription"
# PAYMENT_VERIFICATION = "payment_verification"
