class TestContext:
    current_scheme_account_id = ""
    current_payment_card_id = ""
    name_on_payment_card = ""
    expiry_month = ""
    expiry_year = ""
    card_nickname = ""
    finger_print = ""
    response_json = ""
    response_status_code = ""
    token = ""
    """Variable that decides encryption is required / not"""
    flag_encrypt = ""
    channel_name = ""
