class TestContext:
    current_scheme_account_id = ""
    current_payment_card_id = ""
    second_payment_card_id = ""
    name_on_payment_card = ""
    expiry_month = ""
    expiry_year = ""
    payment_card_token = ""
    finger_print = ""
    card_nickname = ""
    finger_print = ""
    response_json = ""
    response_status_code = ""
    token = ""
    second_token = ""
    error_message = ""
    error_slug = ""
    card_number = ""
    expected_membership_plan_journey_field = ""
    actual_membership_plan_journey_field = ""
    """Variable that decides encryption is required / not"""
    flag_encrypt = ""
    channel_name = ""
